#code for RNAseq analysis of lung and brainstem organotypic cultures, Ferren et al 2020
#naliebe@uw.edu

setwd("~/Desktop")

library(tidyverse)
library(DESeq2)
library(pheatmap)

metadata_file <- file.choose()   
metadata <- read_csv(metadata_file)

lung_meta <- filter(metadata, tissue == "lung")
lung_meta <- column_to_rownames(lung_meta, "sample") 

brain_meta <- filter(metadata, tissue == "brain stem")
brain_meta <- column_to_rownames(brain_meta, "sample")


counts_file <- file.choose() #raw counts file generated by kallisto/tx2gene
counts <- read_csv(counts_file)
counts <- column_to_rownames(counts, "X1") 

lung_counts <- counts[, rownames(lung_meta)]

brain_counts <- counts[, rownames(brain_meta)]

#lung
#normalization
dds_lung <- DESeqDataSetFromMatrix(countData = lung_counts, colData = lung_meta, design= ~ Infection) 
keep <- (rowSums(counts(dds_lung)) >= nrow(lung_meta)) #pre-filter to remove any genes without avg 1 count per sample
dds_lung <- dds_lung[keep,]
dds_lung <- estimateSizeFactors(dds_lung)
norm_counts_lung <- as.data.frame(counts(dds_lung, normalized=TRUE))
colnames(norm_counts_lung) <- c("infected_treated", "infected_untreated", "uninfected")
write.csv(norm_counts_lung, "~/Desktop/hamster_norm_counts_lung.csv")

norm_counts_lung_calcs <- norm_counts_lung + 1
norm_counts_lung_calcs$treated_vs_uninfected_ratio <- norm_counts_lung_calcs$infected_treated / norm_counts_lung_calcs$uninfected
norm_counts_lung_calcs$untreated_vs_uninfected_ratio <- norm_counts_lung_calcs$infected_untreated / norm_counts_lung_calcs$uninfected
norm_counts_lung_calcs$treated_vs_untreated_ratio <- norm_counts_lung_calcs$infected_treated / norm_counts_lung_calcs$infected_untreated

write.csv(norm_counts_lung_calcs, "~/Desktop/lung_counts_and_ratios.csv")

#heatmap 
norm_counts_corr_lung <- filter(norm_counts_lung, uninfected > 5) + 1
FC_lung <- norm_counts_corr_lung / norm_counts_corr_lung$uninfected
l2FC_lung <- log2(FC_lung)
l2FC_lung <- rownames_to_column(l2FC_lung)
most_var_lung <- arrange(l2FC_lung, desc(abs(infected_untreated)))
most_var_lung <- most_var_lung[1:50,]
rownames(most_var_lung) <- most_var_lung$rowname
most_var_lung <- most_var_lung[,-(c(1:2))] 
colnames(most_var_lung) <- c("Infected", "Uninfected")
df_lung <- lung_meta[, c("tissue", "Infection")]  
df_lung <- df_lung[-1, -1, drop=FALSE] #removing CA001 (peptide sample) and tissue (moot)
rownames(df_lung) <- c("Infected", "Uninfected")

alt_lung_names <- read_csv("most_var_lung.csv")
rownames(most_var_lung) <- alt_lung_names$manual_gene_name

png(filename="~/Desktop/hamster_lung_heatmap.png", width=6, height=8, units="in", res=300)
print(pheatmap(most_var_lung, annotation_col=df_lung, show_colnames = F, cluster_cols=FALSE)) 
dev.off()

#brain
#normalization
dds_brain <- DESeqDataSetFromMatrix(countData = brain_counts, colData = brain_meta, design= ~ Infection) 
keep_brain <- (rowSums(counts(dds_brain)) >= nrow(brain_meta)) #pre-filter to remove any genes without avg 1 count per sample
dds_brain <- dds_brain[keep_brain,]
dds_brain <- estimateSizeFactors(dds_brain)
norm_counts_brain <- as.data.frame(counts(dds_brain, normalized=TRUE))
colnames(norm_counts_brain) <- c("infected_treated", "infected_untreated", "uninfected")
write.csv(norm_counts_brain, "~/Desktop/hamster_norm_counts_brain.csv")

norm_counts_brain_calcs <- norm_counts_brain + 1
norm_counts_brain_calcs$treated_vs_uninfected_ratio <- norm_counts_brain_calcs$infected_treated / norm_counts_brain_calcs$uninfected
norm_counts_brain_calcs$untreated_vs_uninfected_ratio <- norm_counts_brain_calcs$infected_untreated / norm_counts_brain_calcs$uninfected
norm_counts_brain_calcs$treated_vs_untreated_ratio <- norm_counts_brain_calcs$infected_treated / norm_counts_brain_calcs$infected_untreated

write.csv(norm_counts_brain_calcs, "~/Desktop/brain_counts_and_ratios.csv")

#heatmap 
norm_counts_corr_brain <- filter(norm_counts_brain, uninfected > 1) + 1
FC_brain <- norm_counts_corr_brain / norm_counts_corr_brain$uninfected
l2FC_brain <- log2(FC_brain)
l2FC_brain <- rownames_to_column(l2FC_brain)
most_var_brain <- arrange(l2FC_brain, desc(abs(infected_untreated)))
most_var_brain <- most_var_brain[1:50,]
rownames(most_var_brain) <- most_var_brain$rowname
most_var_brain <- most_var_brain[,-(c(1:2))]
colnames(most_var_brain) <- c("Infected", "Uninfected")
df_brain <- brain_meta[, c("tissue", "Infection")]
df_brain <- df_brain[-1, -1, drop=FALSE] #removing CA002 (peptide sample) and tissue (moot)
rownames(df_brain) <- c("Infected", "Uninfected")

alt_brain_names <- read_csv("most_var_brain.csv")
rownames(most_var_brain) <- alt_brain_names$manual_gene_name

png(filename="~/Desktop/hamster_brain_heatmap.png", width=6, height=8, units="in", res=300)
print(pheatmap(most_var_brain, annotation_col=df_brain, show_colnames = F, cluster_cols=FALSE)) 
dev.off()


